const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * PDF Report Generation Service
 * Generates professional PDF reports for various system data
 */

class PDFReportService {
  constructor() {
    this.fonts = {
      normal: 'Helvetica',
      bold: 'Helvetica-Bold',
      italic: 'Helvetica-Oblique'
    };
    this.publisherName = 'VIMS - Village Integrated Management System';
    this.brand = {
      primary: '#0f5132',
      primaryDark: '#083b25',
      border: '#d8e6dd',
      rowAlt: '#f5faf7',
      text: '#1d2b24',
      muted: '#62756c'
    };
  }

  /**
   * Adjust timestamp for user's timezone
   * @param {Date} utcDate - Date in UTC
   * @param {number} timezoneOffsetMinutes - Client's timezone offset in minutes (e.g., -480 for UTC+8)
   * @returns {Date} - Date adjusted for client timezone
   */
  _adjustTimestampForTimezone(utcDate, timezoneOffsetMinutes) {
    if (!timezoneOffsetMinutes) return utcDate;
    // timezoneOffsetMinutes is the client-side offset from UTC, as returned by Date.getTimezoneOffset()
    // Local time = UTC time - offset
    return new Date(utcDate.getTime() - timezoneOffsetMinutes * 60000);
  }

  _getTextOptions(overrides = {}) {
    return {
      lineGap: 3,
      characterSpacing: 0.2,
      ...overrides
    };
  }

  _getPublisherName(options = {}) {
    return options.publisherName || this.publisherName;
  }

  _formatDisplayDate(date, timezoneOffsetMinutes = 0) {
    const displayTime = this._adjustTimestampForTimezone(date, timezoneOffsetMinutes);
    return displayTime.toLocaleString('en-US', {
      year: 'numeric',
      month: 'short',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit'
    });
  }

  _formatCreator(creator) {
    if (!creator) return 'VIMS System';
    const name = `${creator.firstName || ''} ${creator.lastName || ''}`.trim() || creator.email || 'VIMS User';
    return creator.role ? `${name} (${creator.role})` : name;
  }

  _escapeCsv(value) {
    if (value === null || value === undefined) return '';
    const normalized = value instanceof Date ? value.toISOString() : String(value);
    return `"${normalized.replace(/"/g, '""')}"`;
  }

  generateCsvReport(title, data, columns, options = {}) {
    const generatedAt = options.generatedAt || new Date();
    const timezoneOffsetMinutes = Number(options.timezoneOffsetMinutes) || 0;
    const publisherName = this._getPublisherName(options);
    const tableRows = Array.isArray(data) ? data : [];
    const tableColumns = Array.isArray(columns) ? columns : [];

    const metadata = [
      ['Publisher', publisherName],
      ['Report', title],
      ['Generated At', this._formatDisplayDate(generatedAt, timezoneOffsetMinutes)],
      ['Generated By', this._formatCreator(options.creator)],
      ['Total Records', tableRows.length]
    ];

    const lines = [
      ...metadata.map((row) => row.map((value) => this._escapeCsv(value)).join(',')),
      '',
      tableColumns.map((col) => this._escapeCsv(col.header || col.label || col.key)).join(','),
      ...tableRows.map((row) => tableColumns.map((col) => {
        const value = this._getNestedValue(row, col.key) ?? row[col.header] ?? row[col.label] ?? '';
        return this._escapeCsv(typeof value === 'object' && !(value instanceof Date) ? JSON.stringify(value) : value);
      }).join(','))
    ];

    return lines.join('\r\n');
  }

  persistReportBuffer(buffer, filename, subdir = 'pdf-exports') {
    const uploadDir = path.join(__dirname, '..', 'uploads', subdir);
    if (!fs.existsSync(uploadDir)) {
      fs.mkdirSync(uploadDir, { recursive: true });
    }
    const filePath = path.join(uploadDir, filename);
    fs.writeFileSync(filePath, buffer);
    return {
      filePath,
      relativeUrl: `/uploads/${subdir}/${filename}`
    };
  }

  /**
   * Generate AI Financial Report PDF
   */
  async generateFinancialReport(data, options = {}) {
    const generatedAt = new Date();
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: 'A4',
          margin: 50,
          bufferPages: true,
          info: {
            Title: 'VIMS Financial Report',
            Author: options.creator ? `${options.creator.firstName} ${options.creator.lastName}` : 'VIMS System',
            Subject: 'Financial Analysis Report'
          }
        });

        const buffers = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
          const pdfBuffer = Buffer.concat(buffers);
          resolve(pdfBuffer);
        });

        this._addReportHeader(doc, 'VIMS Financial Report', data.period, data.year, data.month, options.creator, generatedAt, options.timezoneOffsetMinutes);
        this._addFinancialSummary(doc, data.summary);
        this._addFinancialAnalysis(doc, data.report);
        this._addReportFooter(doc, options.creator, generatedAt, options.timezoneOffsetMinutes);

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  /**
   * Generate AI Visitor Security Report PDF
   */
  async generateVisitorReport(data, options = {}) {
    const generatedAt = new Date();
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: 'A4',
          margin: 50,
          bufferPages: true,
          info: {
            Title: 'VIMS Visitor Security Report',
            Author: options.creator ? `${options.creator.firstName} ${options.creator.lastName}` : 'VIMS System',
            Subject: 'Visitor Security Analysis Report'
          }
        });

        const buffers = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
          const pdfBuffer = Buffer.concat(buffers);
          resolve(pdfBuffer);
        });

        this._addReportHeader(doc, 'VIMS Visitor Security Report', data.period, data.date, null, options.creator, generatedAt, options.timezoneOffsetMinutes);
        this._addVisitorSummary(doc, data.summary);
        this._addVisitorAnalysis(doc, data.report);
        this._addReportFooter(doc, options.creator, generatedAt, options.timezoneOffsetMinutes);

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  /**
   * Generate AI Incident Report PDF
   */
  async generateIncidentReport(data, options = {}) {
    const generatedAt = new Date();
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: 'A4',
          margin: 50,
          bufferPages: true,
          info: {
            Title: 'VIMS Incident Analysis Report',
            Author: options.creator ? `${options.creator.firstName} ${options.creator.lastName}` : 'VIMS System',
            Subject: 'Incident Analysis Report'
          }
        });

        const buffers = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
          const pdfBuffer = Buffer.concat(buffers);
          resolve(pdfBuffer);
        });

        this._addReportHeader(doc, 'VIMS Incident Analysis Report', data.period, data.date, null, options.creator, generatedAt, options.timezoneOffsetMinutes);
        this._addIncidentSummary(doc, data.summary);
        this._addIncidentAnalysis(doc, data.report);
        this._addReportFooter(doc, options.creator, generatedAt, options.timezoneOffsetMinutes);

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  /**
   * Generate General Data Report PDF (for non-AI reports)
   */
  async generateDataReport(title, data, columns, options = {}) {
    const generatedAt = new Date();
    return new Promise((resolve, reject) => {
      try {
        console.log(`Generating PDF report: ${title}, ${data.length} rows, ${columns.length} columns`);

        const doc = new PDFDocument({
          size: options.size || 'A4',
          layout: options.layout || 'portrait',
          margin: options.margin || 50,
          bufferPages: true,
          info: {
            Title: title,
            Author: options.creator ? `${options.creator.firstName} ${options.creator.lastName}` : 'VIMS System',
            Subject: `${title} Report`
          }
        });

        const buffers = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
          const pdfBuffer = Buffer.concat(buffers);
          if (options.persistFilename) {
            this.persistReportBuffer(pdfBuffer, options.persistFilename, options.persistSubdir);
          }
          console.log(`PDF generation completed, buffer size: ${pdfBuffer.length} bytes`);
          resolve(pdfBuffer);
        });

        doc.on('error', (error) => {
          console.error('PDF generation error:', error);
          reject(error);
        });

        this._addReportHeader(doc, title, 'Generated', generatedAt.toLocaleDateString(), null, options.creator, generatedAt, options.timezoneOffsetMinutes, options);
        if (options.summary) {
          this._addLotStatusSummary(doc, options.summary);
        }
        this._addDataTable(doc, data, columns, options.table || {});
        this._addReportFooter(doc, options.creator, generatedAt, options.timezoneOffsetMinutes);

        doc.end();
      } catch (error) {
        console.error('PDF generation failed:', error);
        reject(error);
      }
    });
  }

  _addReportHeader(doc, title, period, date, month, creator, generatedAt = new Date(), timezoneOffsetMinutes = 0, options = {}) {
    const left = doc.page.margins.left;
    const usableWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const publisherName = this._getPublisherName(options);
    const displayTime = this._formatDisplayDate(generatedAt, timezoneOffsetMinutes);

    doc.rect(0, 0, doc.page.width, 86).fill(this.brand.primary);
    doc.fillColor('#ffffff').fontSize(17).font(this.fonts.bold)
      .text(publisherName, left, 24, this._getTextOptions({ width: usableWidth, align: 'left' }));
    doc.fontSize(9.5).font(this.fonts.normal)
      .text('Official system export report', left, 50, this._getTextOptions({ width: usableWidth, align: 'left' }));

    doc.y = 110;
    doc.fillColor(this.brand.text).fontSize(18).font(this.fonts.bold)
      .text(title, left, doc.y, this._getTextOptions({ width: usableWidth, align: 'left' }));

    const metaParts = [`Generated: ${displayTime}`, `Publisher: ${publisherName}`];
    if (period && date) metaParts.unshift(`${period}: ${date}${month ? `/${month}` : ''}`);
    metaParts.push(`Generated by: ${this._formatCreator(creator)}`);

    doc.moveDown(0.65);
    doc.fillColor(this.brand.muted).fontSize(9.5).font(this.fonts.normal)
      .text(metaParts.join('   |   '), this._getTextOptions({ width: usableWidth, align: 'left' }));

    doc.moveDown(1);
    doc.strokeColor(this.brand.border).lineWidth(1)
      .moveTo(left, doc.y).lineTo(left + usableWidth, doc.y).stroke();
    doc.moveDown(1.25);
  }

  _addFinancialSummary(doc, summary) {
    doc.fontSize(14).font(this.fonts.bold).text('Financial Summary', { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11).font(this.fonts.normal);
    doc.text(`Total Revenue: ₱${summary.totalRevenue.toLocaleString()}`, this._getTextOptions());
    doc.text(`Number of Payments: ${summary.paymentCount}`, this._getTextOptions());
    doc.text(`Total Residents: ${summary.totalUsers}`, this._getTextOptions());
    doc.text(`New Residents: ${summary.newUsers}`, this._getTextOptions());
    doc.text(`Average Payment: ₱${summary.paymentCount > 0 ? Math.round(summary.totalRevenue / summary.paymentCount).toLocaleString() : 0}`, this._getTextOptions());

    doc.moveDown(1);
  }

  _addVisitorSummary(doc, summary) {
    doc.fontSize(14).font(this.fonts.bold).text('Visitor Summary', { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11).font(this.fonts.normal);
    doc.text(`Total Visitors: ${summary.totalVisitors}`, this._getTextOptions());
    doc.text(`Approved: ${summary.approvedVisitors}`, this._getTextOptions());
    doc.text(`Pending: ${summary.pendingVisitors}`, this._getTextOptions());
    doc.text(`Rejected: ${summary.rejectedVisitors}`, this._getTextOptions());
    doc.text(`Approval Rate: ${summary.totalVisitors > 0 ? Math.round((summary.approvedVisitors / summary.totalVisitors) * 100) : 0}%`, this._getTextOptions());

    doc.moveDown(1);
  }

  _addIncidentSummary(doc, summary) {
    doc.fontSize(14).font(this.fonts.bold).text('Incident Summary', { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11).font(this.fonts.normal);
    doc.text(`Total Incidents: ${summary.totalIncidents}`, this._getTextOptions());
    doc.text(`Resolved: ${summary.resolvedIncidents}`, this._getTextOptions());
    doc.text(`Pending: ${summary.pendingIncidents}`, this._getTextOptions());
    doc.text(`Urgent: ${summary.urgentIncidents}`, this._getTextOptions());
    doc.text(`Resolution Rate: ${summary.totalIncidents > 0 ? Math.round((summary.resolvedIncidents / summary.totalIncidents) * 100) : 0}%`, this._getTextOptions());

    doc.moveDown(1);
  }

  _addFinancialAnalysis(doc, analysis) {
    doc.fontSize(14).font(this.fonts.bold).text('AI Financial Analysis', { underline: true });
    doc.moveDown(0.5);
    this._addWrappedText(doc, analysis, 11);
  }

  _addVisitorAnalysis(doc, analysis) {
    doc.fontSize(14).font(this.fonts.bold).text('AI Visitor Security Analysis', { underline: true });
    doc.moveDown(0.5);
    this._addWrappedText(doc, analysis, 11);
  }

  _addIncidentAnalysis(doc, analysis) {
    doc.fontSize(14).font(this.fonts.bold).text('AI Incident Analysis', { underline: true });
    doc.moveDown(0.5);
    this._addWrappedText(doc, analysis, 11);
  }

  _addDataTable(doc, data, columns, options = {}) {
    if (!data || data.length === 0) {
      doc.fontSize(11).text('No data available for this report.');
      return;
    }

    const startX = doc.page.margins.left;
    const usableWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const bottomY = doc.page.height - doc.page.margins.bottom - 58;
    const headerFontSize = options.headerFontSize || 8.5;
    const bodyFontSize = options.bodyFontSize || 8;
    const cellPadding = options.cellPadding ?? 4;
    const maxRows = options.maxRows || 50;
    const totalColWidth = columns.reduce((sum, col) => sum + (col.width || 10), 0);
    const colWidths = columns.map((col) => ((col.width || 10) / totalColWidth) * usableWidth);

    const drawHeader = (yPosition) => {
      let x = startX;
      doc.fontSize(headerFontSize).font(this.fonts.bold).fillColor('#fff');
      const headerHeights = columns.map((col, index) => {
        const width = colWidths[index];
        const headerText = col.header || col.label || col.key || 'Unknown';
        return doc.heightOfString(headerText, {
          width: Math.max(width - cellPadding * 2, 8),
          align: 'left'
        });
      });
      const headerHeight = Math.max(...headerHeights, 12) + cellPadding * 2;

      columns.forEach((col, index) => {
        const width = colWidths[index];
        const headerText = col.header || col.label || col.key || 'Unknown';
        doc.rect(x, yPosition, width, headerHeight).fill(this.brand.primary);
        doc.fillColor('#fff').font(this.fonts.bold);
        doc.text(headerText, x + cellPadding, yPosition + cellPadding, this._getTextOptions({
          width: Math.max(width - cellPadding * 2, 8),
          align: 'left'
        }));
        x += width;
      });
      doc.strokeColor(this.brand.primaryDark).moveTo(startX, yPosition + headerHeight).lineTo(startX + usableWidth, yPosition + headerHeight).stroke();
      return yPosition + headerHeight + 4;
    };

    let yPosition = drawHeader(doc.y + 10);
    doc.fontSize(bodyFontSize).font(this.fonts.normal).fillColor(this.brand.text);

    data.slice(0, maxRows).forEach((row, rowIndex) => {
      const rowValues = columns.map((col) => {
        const value = this._getNestedValue(row, col.key) ?? '';
        return typeof value === 'object' ? JSON.stringify(value) : String(value);
      });

      const rowHeights = rowValues.map((value, index) => doc.heightOfString(value, {
        width: Math.max(colWidths[index] - cellPadding * 2, 8),
        align: 'left'
      }));

      const rowHeight = Math.max(...rowHeights, 12) + cellPadding * 2;

      if (yPosition + rowHeight > bottomY) {
        doc.addPage();
        yPosition = drawHeader(doc.page.margins.top);
        doc.fontSize(bodyFontSize).font(this.fonts.normal).fillColor(this.brand.text);
      }

      let x = startX;
      if (rowIndex % 2 === 1) {
        doc.rect(startX, yPosition, usableWidth, rowHeight).fill(this.brand.rowAlt);
      }
      doc.fontSize(bodyFontSize).font(this.fonts.normal).fillColor(this.brand.text);
      rowValues.forEach((text, index) => {
        doc.text(text, x + cellPadding, yPosition + cellPadding, this._getTextOptions({
          width: Math.max(colWidths[index] - cellPadding * 2, 8),
          align: 'left'
        }));
        x += colWidths[index];
      });

      yPosition += rowHeight;
      doc.strokeColor(this.brand.border).lineWidth(0.6).moveTo(startX, yPosition).lineTo(startX + usableWidth, yPosition).stroke();
    });

    if (data.length > maxRows) {
      doc.moveDown(1);
      doc.fontSize(10).text(`... and ${data.length - maxRows} more records`);
    }
  }

  _addLotStatusSummary(doc, summary) {
    doc.fontSize(14).font(this.fonts.bold).text('Lot Status Summary', this._getTextOptions({ underline: true }));
    doc.moveDown(0.5);
    doc.fontSize(11).font(this.fonts.normal);
    doc.text(`Total lots included: ${summary.total}`, this._getTextOptions());
    if (typeof summary.occupied === 'number') {
      doc.text(`Occupied lots: ${summary.occupied}`, this._getTextOptions());
    }
    if (typeof summary.vacant === 'number') {
      doc.text(`Vacant lots: ${summary.vacant}`, this._getTextOptions());
    }
    if (typeof summary.reserved === 'number') {
      doc.text(`Reserved lots: ${summary.reserved}`, this._getTextOptions());
    }
    if (typeof summary.other === 'number') {
      doc.text(`Other status lots: ${summary.other}`, this._getTextOptions());
    }
    doc.moveDown(1);
  }

  _addWrappedText(doc, text, fontSize = 11) {
    doc.fontSize(fontSize).font(this.fonts.normal);

    const lines = text.split('\n');
    lines.forEach(line => {
      const words = line.split(' ');
      let currentLine = '';

      words.forEach(word => {
        const testLine = currentLine + (currentLine ? ' ' : '') + word;
        const width = doc.widthOfString(testLine);

        if (width > 495 && currentLine) {
          doc.text(currentLine, this._getTextOptions({ width: 495, align: 'left' }));
          currentLine = word;
        } else {
          currentLine = testLine;
        }
      });

      if (currentLine) {
        doc.text(currentLine, this._getTextOptions({ width: 495, align: 'left' }));
      }
    });
  }

  _addReportFooter(doc, creator, generatedAt = new Date(), timezoneOffsetMinutes = 0) {
    // Adjust timestamp for timezone
    const displayTime = this._adjustTimestampForTimezone(generatedAt, timezoneOffsetMinutes);

    const pageRange = doc.bufferedPageRange();
    const pageCount = pageRange.count;
    const startPage = pageRange.start || 0;

    for (let i = 0; i < pageCount; i++) {
      const pageIndex = startPage + i;
      doc.switchToPage(pageIndex);

      // Footer line
      const left = doc.page.margins.left;
      const usableWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
      const footerY = doc.page.height - doc.page.margins.bottom - 20;
      doc.strokeColor(this.brand.border).moveTo(left, footerY).lineTo(left + usableWidth, footerY).stroke();

      doc.fillColor(this.brand.muted).fontSize(8).font(this.fonts.normal);
      doc.text(this.publisherName, left, footerY + 10, this._getTextOptions({ width: usableWidth, align: 'center' }));
      doc.text(`Page ${i + 1} of ${pageCount}`, left, footerY + 10, this._getTextOptions({ width: usableWidth, align: 'right' }));
      doc.text(`Generated on ${this._formatDisplayDate(generatedAt, timezoneOffsetMinutes)}`, left, footerY + 22, this._getTextOptions({ width: usableWidth, align: 'center' }));

      if (creator) {
        doc.text(`Generated by: ${this._formatCreator(creator)}`, left, footerY + 34, this._getTextOptions({ width: usableWidth, align: 'center' }));
      }
    }
  }

  _getNestedValue(obj, path) {
    return path.split('.').reduce((current, key) => current && current[key], obj);
  }
}

module.exports = new PDFReportService();
