import React, { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Modal, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import api from '../utils/api';
import { themeColors } from '../utils/theme';
import VisitorOverstayChatModal from './VisitorOverstayChatModal';

const residentName = (row) => `${row.resident?.firstName || ''} ${row.resident?.lastName || ''}`.trim() || 'Resident';

export default function OverstayChatInboxModal({ visible, onClose }) {
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(false); const [visitor, setVisitor] = useState(null);
  const load = async () => { if (!visible) return; setLoading(true); try { const response = await api.get('/visitors/overstay-chats'); setRows(response.data?.data || []); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [visible]);
  const renderItem = ({ item }) => <TouchableOpacity style={styles.caseCard} onPress={() => setVisitor(item.visitor)} activeOpacity={.82}><View style={styles.caseTop}><View style={styles.caseTitleWrap}><View style={styles.warningIcon}><Ionicons name="warning" size={18} color="#c2410c" /></View><View><Text style={styles.visitorName}>{item.visitor?.visitorName || 'Visitor'}</Text><Text style={styles.overstayLabel}>OVERSTAYING VISITOR</Text></View></View><View style={styles.statusPill}><Text style={styles.statusText}>OVERSTAYING</Text></View></View><View style={styles.infoBlock}><Text style={styles.infoLine}><Ionicons name="person-outline" size={15} color={themeColors.textSecondary} />  Resident Name — <Text style={styles.infoValue}>{residentName(item)}</Text></Text><Text style={styles.infoLine}><Ionicons name="home-outline" size={15} color={themeColors.textSecondary} />  Lot Address — <Text style={styles.infoValue}>{item.resident?.houseNumber || 'Not recorded'}</Text></Text><Text style={styles.infoLine}><Ionicons name="location-outline" size={15} color={themeColors.textSecondary} />  Visitor Name — <Text style={styles.infoValue}>{item.visitor?.visitorName || 'Visitor'}</Text></Text></View><View style={styles.preview}><Ionicons name="chatbubble-ellipses-outline" size={16} color={themeColors.primary} /><Text numberOfLines={1} style={styles.previewText}>{item.lastMessage?.body || 'Open conversation'}</Text><Ionicons name="chevron-forward" size={17} color={themeColors.textSecondary} /></View></TouchableOpacity>;
  return <><Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.sheet}><View style={styles.header}><View style={styles.headerTitleRow}><View style={styles.headerIcon}><Ionicons name="warning" size={21} color="#c2410c" /></View><View><Text style={styles.title}>Overstay messages</Text><Text style={styles.sub}>Active resident–security follow-ups only</Text></View></View><TouchableOpacity onPress={onClose}><Ionicons name="close" size={24} color={themeColors.textPrimary} /></TouchableOpacity></View>{loading ? <ActivityIndicator style={{ flex: 1 }} color={themeColors.primary} /> : <FlatList data={rows} keyExtractor={(row) => row.visitor?._id} contentContainerStyle={rows.length ? styles.list : styles.empty} ListEmptyComponent={<Text style={styles.emptyText}>No active overstaying visitor conversations yet.</Text>} renderItem={renderItem} />}</View></View></Modal><VisitorOverstayChatModal visible={Boolean(visitor)} visitor={visitor} onClose={() => { setVisitor(null); load(); }} /></>;
}
const styles = StyleSheet.create({ backdrop:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(15,23,42,.5)'},sheet:{height:'78%',backgroundColor:'#f8fafc',borderTopLeftRadius:24,borderTopRightRadius:24,padding:18},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingBottom:14,borderBottomWidth:1,borderBottomColor:'#e2e8f0'},headerTitleRow:{flexDirection:'row',alignItems:'center',gap:10},headerIcon:{width:39,height:39,borderRadius:12,alignItems:'center',justifyContent:'center',backgroundColor:'#fff7ed'},title:{fontSize:21,fontWeight:'900',color:themeColors.textPrimary},sub:{marginTop:3,fontSize:12,color:themeColors.textSecondary},list:{paddingVertical:12,gap:10},caseCard:{backgroundColor:'#fff',borderWidth:1,borderColor:'#fed7aa',borderRadius:16,padding:14},caseTop:{flexDirection:'row',justifyContent:'space-between',gap:8},caseTitleWrap:{flexDirection:'row',alignItems:'center',gap:9,flex:1},warningIcon:{width:36,height:36,borderRadius:18,alignItems:'center',justifyContent:'center',backgroundColor:'#fff7ed'},visitorName:{fontSize:16,fontWeight:'900',color:'#9a3412'},overstayLabel:{fontSize:10,fontWeight:'900',letterSpacing:.6,color:'#ea580c',marginTop:2},statusPill:{backgroundColor:'#fff1f2',borderWidth:1,borderColor:'#fecaca',borderRadius:12,paddingHorizontal:8,paddingVertical:5},statusText:{color:'#dc2626',fontSize:9,fontWeight:'900'},infoBlock:{marginTop:12,gap:6},infoLine:{fontSize:12,color:themeColors.textSecondary,lineHeight:18},infoValue:{fontWeight:'800',color:themeColors.textPrimary},preview:{marginTop:12,paddingTop:10,borderTopWidth:1,borderTopColor:'#f1f5f9',flexDirection:'row',alignItems:'center',gap:7},previewText:{flex:1,fontSize:12,color:themeColors.textSecondary},empty:{flexGrow:1,justifyContent:'center',alignItems:'center',padding:30},emptyText:{textAlign:'center',color:themeColors.textSecondary,lineHeight:20}, });
